---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: citadel
  namespace: industries

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: citadel-log-reader
  namespace: industries
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: citadel-log-reader-binding
  namespace: industries
subjects:
  - kind: ServiceAccount
    name: citadel
    namespace: industries
roleRef:
  kind: Role
  name: citadel-log-reader
  apiGroup: rbac.authorization.k8s.io
