---
apiVersion: v1
kind: ConfigMap
metadata:
  name: moria-config
  namespace: industries
data:
  config.json: |
    {
      "database": {
        "path": "/app/data/moria.db",
        "schema": "./schema/model.sql"
      },
      "server": {
        "port": "8081"
      },
      "internal": {
        "port": "8082"
      }
    }
