---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shire
  namespace: industries
spec:
  selector:
    matchLabels:
      app: shire
  template:
    metadata:
      labels:
        app: shire
    spec:
      containers:
        - name: shire
          image: julianone/shire:latest
          env:
            - name: MORIA_API_URL
              value: http://moria.industries.svc.cluster.local
            - name: ORIGIN
              value: https://julian-one.com
          readinessProbe:
            httpGet:
              path: /
              port: 3000
